name: CI Pipeline

on:
  push:
    branches:
      - 'main'
      - 'release/**'
      - 'feature/**'
  pull_request:
    branches:
      - 'main'
      - 'release/**'
      - 'feature/**'

jobs:
  validate-branch:
    name: Validate Branch Policy
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Check source/target branch rules
        run: |
          echo "Source: ${{ github.head_ref }}"
          echo "Target: ${{ github.base_ref }}"

          TARGET=${{ github.base_ref }}
          SOURCE=${{ github.head_ref }}

          if [[ "$TARGET" == "main" && "$SOURCE" != release/* ]]; then
            echo "❌ Only release branches can be merged into main"
            exit 1
          fi

          if [[ "$TARGET" == release/* && "$SOURCE" != feature/* ]]; then
            echo "❌ Only feature branches can be merged into release"
            exit 1
          fi

          if [[ "$TARGET" == feature/* && "$SOURCE" != feature/* ]]; then
            echo "❌ Only feature branches can be merged into other feature branches"
            exit 1
          fi

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: validate-branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build with Maven (skip tests)
        run: mvn clean install -DskipTests

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Run tests if present
        run: |
          if ls src/test/java | grep -q .; then
            mvn test
          else
            echo "✅ No unit tests found. Skipping test job."
